Draft API spec (v1.0)
cs-24-sw-2-14/MagicBoard-server pull request #6
Opened 2024-04-11 09:08 UTC by krestenlaust

2024-04-11 16:04 UTC, Many5900 approved these changes
### HYMMMM, DET GÅR VEL AN

2024-04-17 13:11 UTC, krestenlaust commented
Sikkert fint

2024-04-18 13:11 UTC, tbdlarsen reviewed
fin nok kode mangler lidt "content" og maaske nogle bedre "discribtions"
@krestenlaust 

:+1:

2024-04-18 13:11 UTC, tbdlarsen commented on API/rest-api.yaml
> +    Write short description.
host host

2024-04-18 13:11 UTC, tbdlarsen commented on API/rest-api.yaml
> +          $ref: '#/components/responses/board_uid_missing'
i orden her til

2024-04-18 13:11 UTC, tbdlarsen commented on API/rest-api.yaml
> +
good

2024-04-18 13:41 UTC, krestenlaust commented on API/rest-api.yaml
> +
Tak 😊

2024-04-18 13:42 UTC, krestenlaust commented on API/rest-api.yaml
> +          $ref: '#/components/responses/board_uid_missing'
😱

2024-04-23 08:21 UTC, Many5900 requested changes

2024-04-23 08:21 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/czech_uid:
Kan vi ikke undgå Heterograph/Homophone ord?

2024-04-23 08:21 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/inpect_UID:
Hved ikke lige om "inpect" var meget bedre... Hvad med "doExist" eller "check"...

2024-04-23 08:26 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/doExist:
Skal vi ikke koere snakecase? Hvad med "do_uid_exist"?

2024-04-23 08:28 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/doExist:
Maaske bedre med "do_ board_uid_exist". Det er mere sigende

2024-04-23 08:28 UTC, Many5900 requested changes
.

2024-04-23 08:31 UTC, tbdlarsen commented on API/rest-api.yaml
> +  /v1/board/doExist:
wym det var legit din ide at kalde den DoExitst

2024-04-23 08:33 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/doExist:
<3

2024-04-23 08:34 UTC, Many5900 commented on API/rest-api.yaml
> +  /v1/board/doExist:
Man maa gerne taenke selv

2024-04-23 08:42 UTC, krestenlaust commented on API/rest-api.yaml
> +  /v1/board/inpect_UID:
Vi styrede udenom homonymer

2024-04-24 06:22 UTC, krestenlaust commented on API/rest-api.yaml
> +  /v1/board/doExist:
I've found an appropriate middleground

2024-04-25 08:18 UTC, Many5900 approved these changes
NICE!

2024-04-25 08:20 UTC, MadsLudvig commented
hmm do you really think that it is appropriate to start at 1.0?

2024-04-25 08:32 UTC, merged